#!/bin/bash

REVTEST_ROOT=$(pwd)
REVTEST_TEST=$(realpath $1)

echo "$REVTEST_TEST"

source $REVTEST_TEST

cd $REVTEST_REPO
prepare_repo


iTest=0
while true; do
	((iTest++))
	COMMIT=$(git rev-parse --verify HEAD)

	echo "Currently testing commit $COMMIT"
	$REVTEST_TEST

	if [ $? -eq 0 ]; then
		echo "  -> Working version found $COMMIT."
		break
	fi
	
	if [ $iTest -gt $REVTEST_MAX_TESTS ]; then
		echo "  Max iterations reached $iTest".
		break
	fi

	git stash > /dev/null 2>&1
	git checkout HEAD~1 > /dev/null 2>&1

	if [ $? -ne 0 ]; then
		echo "  End of repo reached."
		break
	fi

done



